### ISSUE TITLE
definire la struttura dei dati

### ISSUE THREAD

**Issue by moebiusmania** [edgemony-coding-bootcamp/project-salvatore-b#2]
- quali endpoint ci servono?
- come saranno strutturati i dati nei vari endpoint?

**Comment by MirMara** [comment]
GET /products
GET /products/1
GET /products/categories
GET /products/category/jewelery
GET /cart?userId=1
GET /products?limit=5

https://fakestoreapi.com/products

keys: id, title,  price,  description, category, image, rating
